# Generated by Django 5.2.8 on 2025-11-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_externo', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reloj_lamport', models.BigIntegerField()),
                ('prioridad_id', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('EN_COLA', 'EN_COLA'), ('CONCEDIDA', 'CONCEDIDA'), ('ACTIVA', 'ACTIVA'), ('LIBERADA', 'LIBERADA'), ('CANCELADA', 'CANCELADA'), ('EXPIRADA', 'EXPIRADA')], max_length=16)),
                ('fecha_concesion', models.DateTimeField(blank=True, null=True)),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.recurso')),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='reserva_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurso_actual_de', to='reservas.reserva'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=32)),
                ('ts_cliente', models.BigIntegerField(blank=True, null=True)),
                ('ts_servidor', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['recurso', 'estado', 'reloj_lamport', 'prioridad_id'], name='ix_reservas_cola'),
        ),
    ]
