# Generated by Django 5.2.8 on 2025-11-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='estado_recurso',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='DISPONIBLE', max_length=16),
        ),
        migrations.AddField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificador_externo',
            field=models.CharField(help_text='Identificador del nodo (ej. A, B, C, nodo-1, etc.)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='datos',
            field=models.JSONField(blank=True, help_text='Información adicional (por ejemplo, estado anterior/nuevo, nodo, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ts_cliente',
            field=models.BigIntegerField(blank=True, help_text='Timestamp lógico o físico reportado por el cliente (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('EN_COLA', 'En cola'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='prioridad_id',
            field=models.CharField(help_text='Usado para desempate determinístico entre dos timestamps iguales', max_length=64),
        ),
    ]
